#!/bin/sh

if ! uci -q get frpc.common.enabled >/dev/null; then
	uci -q set frpc.common.enabled='false'
	uci -q commit frpc
fi

uci -q batch <<-EOF >/dev/null
	add ucitrack frpc
	set ucitrack.@frpc[-1].init=frpc
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
