#!/bin/sh

changed=0

if ! uci -q get frpc.common.enabled >/dev/null; then
	uci -q set frpc.common.enabled='false'
	changed=1
fi

if ! uci -q get frpc.common.store_enable >/dev/null; then
	uci -q set frpc.common.store_enable='false'
	changed=1
fi

if ! uci -q get frpc.common.store_path >/dev/null; then
	uci -q set frpc.common.store_path='/etc/frpc/frpc_store.json'
	changed=1
fi

if [ "$changed" = "1" ]; then
	uci -q commit frpc
fi

uci -q batch <<-EOF >/dev/null
	add ucitrack frpc
	set ucitrack.@frpc[-1].init=frpc
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
