#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

NAME="frps"
BIN="/usr/bin/frps"
CONFIG_FOLDER="/var/etc/$NAME"
SYNC_STATE_DIR="/etc/frp/$NAME.d"
SYNC_STATE_FILE="$SYNC_STATE_DIR/status"

_read_sync_status() {
	[ -f "$SYNC_STATE_FILE" ] || return 0
	_trim_ws "$(cat "$SYNC_STATE_FILE" 2>/dev/null)"
}

_write_sync_status() {
	local value="$1"

	mkdir -p "$SYNC_STATE_DIR"
	if [ -n "$value" ]; then
		printf '%s\n' "$value" > "$SYNC_STATE_FILE"
	else
		: > "$SYNC_STATE_FILE"
	fi
}

_trim_ws() {
	local value="$1"
	value="${value%"${value##*[![:space:]]}"}"
	value="${value#"${value%%[![:space:]]*}"}"
	printf '%s' "$value"
}

_toml_escape() {
	printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

_toml_quote() {
	printf '"%s"' "$(_toml_escape "$1")"
}

_toml_write_string() {
	local file="$1"
	local key="$2"
	local value="$3"
	[ -n "$value" ] || return 0
	printf '%s = %s\n' "$key" "$(_toml_quote "$value")" >> "$file"
}

_toml_write_bool() {
	local file="$1"
	local key="$2"
	local value="$3"
	case "$value" in
		1|true|TRUE|yes|on)
			printf '%s = true\n' "$key" >> "$file"
			;;
		0|false|FALSE|no|off)
			printf '%s = false\n' "$key" >> "$file"
			;;
	esac
}

_toml_write_int() {
	local file="$1"
	local key="$2"
	local value="$3"
	[ -n "$value" ] || return 0
	printf '%s = %s\n' "$key" "$value" >> "$file"
}

_toml_write_csv_array() {
	local file="$1"
	local key="$2"
	local value="$3"
	local item arr sep old_ifs

	[ -n "$value" ] || return 0
	old_ifs="$IFS"
	IFS=,
	for item in $value; do
		item="$(_trim_ws "$item")"
		[ -n "$item" ] || continue
		arr="${arr}${sep}$(_toml_quote "$item")"
		sep=", "
	done
	IFS="$old_ifs"
	[ -n "$arr" ] || return 0
	printf '%s = [%s]\n' "$key" "$arr" >> "$file"
}

_toml_write_allow_ports() {
	local file="$1"
	local value="$2"
	local old_ifs part result sep single start end

	[ -n "$value" ] || return 0
	old_ifs="$IFS"
	IFS='}'
	for part in $value; do
		part="$(_trim_ws "${part#\{}")"
		part="${part#,}"
		part="$(_trim_ws "$part")"
		[ -n "$part" ] || continue

		single="$(printf '%s' "$part" | sed -n 's/.*single[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		if [ -n "$single" ]; then
			result="${result}${sep}{ single = $single }"
			sep=", "
			continue
		fi

		start="$(printf '%s' "$part" | sed -n 's/.*start[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		end="$(printf '%s' "$part" | sed -n 's/.*end[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		if [ -n "$start" ] && [ -n "$end" ]; then
			result="${result}${sep}{ start = $start, end = $end }"
			sep=", "
		fi
	done
	IFS="$old_ifs"
	[ -n "$result" ] || return 0
	printf 'allowPorts = [%s]\n' "$result" >> "$file"
}

_toml_collect_item() {
	local item="$1"
	[ -n "$item" ] || return 0
	if [ -n "$TOML_LIST" ]; then
		TOML_LIST="$TOML_LIST, $(_toml_quote "$item")"
	else
		TOML_LIST="$(_toml_quote "$item")"
	fi
}

_load_env() {
	local env="$1"
	[ -n "$env" ] || return 0
	procd_append_param env "$env"
}

_append_common() {
	local section="$1"
	local file="$2"
	local bind_addr bind_port bind_udp_port kcp_bind_port quic_bind_port proxy_bind_addr
	local vhost_http_port vhost_https_port vhost_http_timeout dashboard_addr dashboard_port dashboard_user
	local dashboard_pwd dashboard_tls_mode dashboard_tls_cert_file dashboard_tls_key_file assets_dir
	local log_file log_level log_max_days disable_log_color auth_method token oidc_issuer oidc_audience
	local subdomain_host tcp_mux custom_404_page allow_ports max_ports_per_client heartbeat_timeout

	config_get bind_addr "$section" bind_addr
	config_get bind_port "$section" bind_port
	config_get bind_udp_port "$section" bind_udp_port
	config_get kcp_bind_port "$section" kcp_bind_port
	config_get quic_bind_port "$section" quic_bind_port
	config_get proxy_bind_addr "$section" proxy_bind_addr
	config_get vhost_http_port "$section" vhost_http_port
	config_get vhost_https_port "$section" vhost_https_port
	config_get vhost_http_timeout "$section" vhost_http_timeout
	config_get dashboard_addr "$section" dashboard_addr
	config_get dashboard_port "$section" dashboard_port
	config_get dashboard_user "$section" dashboard_user
	config_get dashboard_pwd "$section" dashboard_pwd
	config_get_bool dashboard_tls_mode "$section" dashboard_tls_mode 0
	config_get dashboard_tls_cert_file "$section" dashboard_tls_cert_file
	config_get dashboard_tls_key_file "$section" dashboard_tls_key_file
	config_get assets_dir "$section" assets_dir
	config_get log_file "$section" log_file
	config_get log_level "$section" log_level
	config_get log_max_days "$section" log_max_days
	config_get_bool disable_log_color "$section" disable_log_color 0
	config_get auth_method "$section" auth_method token
	config_get token "$section" token
	config_get oidc_issuer "$section" oidc_issuer
	config_get oidc_audience "$section" oidc_audience
	config_get subdomain_host "$section" subdomain_host
	config_get_bool tcp_mux "$section" tcp_mux 1
	config_get custom_404_page "$section" custom_404_page
	config_get allow_ports "$section" allow_ports
	config_get max_ports_per_client "$section" max_ports_per_client
	config_get heartbeat_timeout "$section" heartbeat_timeout

	_toml_write_string "$file" bindAddr "$bind_addr"
	_toml_write_int "$file" bindPort "$bind_port"
	_toml_write_int "$file" bindUdpPort "$bind_udp_port"
	_toml_write_int "$file" kcpBindPort "$kcp_bind_port"
	_toml_write_int "$file" quicBindPort "$quic_bind_port"
	_toml_write_string "$file" proxyBindAddr "$proxy_bind_addr"
	_toml_write_int "$file" vhostHTTPPort "$vhost_http_port"
	_toml_write_int "$file" vhostHTTPSPort "$vhost_https_port"
	_toml_write_int "$file" vhostHTTPTimeout "$vhost_http_timeout"
	_toml_write_string "$file" webServer.addr "$dashboard_addr"
	_toml_write_int "$file" webServer.port "$dashboard_port"
	_toml_write_string "$file" webServer.user "$dashboard_user"
	_toml_write_string "$file" webServer.password "$dashboard_pwd"
	_toml_write_bool "$file" webServer.tls.enable "$dashboard_tls_mode"
	_toml_write_string "$file" webServer.tls.certFile "$dashboard_tls_cert_file"
	_toml_write_string "$file" webServer.tls.keyFile "$dashboard_tls_key_file"
	_toml_write_string "$file" webServer.assetsDir "$assets_dir"
	_toml_write_string "$file" log.to "$log_file"
	_toml_write_string "$file" log.level "$log_level"
	_toml_write_int "$file" log.maxDays "$log_max_days"
	_toml_write_bool "$file" log.disablePrintColor "$disable_log_color"
	_toml_write_string "$file" auth.method "$auth_method"

	case "$auth_method" in
		oidc)
			_toml_write_string "$file" auth.oidc.issuer "$oidc_issuer"
			_toml_write_string "$file" auth.oidc.audience "$oidc_audience"
			;;
		*)
			_toml_write_string "$file" auth.token "$token"
			;;
	esac

	_toml_write_string "$file" subdomainHost "$subdomain_host"
	_toml_write_bool "$file" transport.tcpMux "$tcp_mux"
	_toml_write_string "$file" custom404Page "$custom_404_page"
	_toml_write_allow_ports "$file" "$allow_ports"
	_toml_write_int "$file" maxPortsPerClient "$max_ports_per_client"
	_toml_write_int "$file" transport.heartbeatTimeout "$heartbeat_timeout"

	TOML_LIST=
	config_list_foreach main conf_inc _toml_collect_item
	[ -n "$TOML_LIST" ] && printf 'includes = [%s]\n' "$TOML_LIST" >> "$file"
}

_sync_common_option() {
	case "$1" in
		bind_addr|bind_port|bind_udp_port|kcp_bind_port|quic_bind_port|proxy_bind_addr|vhost_http_port|vhost_https_port|vhost_http_timeout|dashboard_addr|dashboard_port|dashboard_user|dashboard_pwd|dashboard_tls_mode|dashboard_tls_cert_file|dashboard_tls_key_file|assets_dir|log_file|log_level|log_max_days|disable_log_color|auth_method|token|oidc_issuer|oidc_audience|subdomain_host|tcp_mux|custom_404_page|allow_ports|max_ports_per_client|heartbeat_timeout|conf_inc)
			printf '%s' "$1"
			;;
		auth.method)
			printf '%s' 'auth_method'
			;;
		bindAddr)
			printf '%s' 'bind_addr'
			;;
		bindPort)
			printf '%s' 'bind_port'
			;;
		bindUdpPort)
			printf '%s' 'bind_udp_port'
			;;
		kcpBindPort)
			printf '%s' 'kcp_bind_port'
			;;
		quicBindPort)
			printf '%s' 'quic_bind_port'
			;;
		proxyBindAddr)
			printf '%s' 'proxy_bind_addr'
			;;
		vhostHTTPPort)
			printf '%s' 'vhost_http_port'
			;;
		vhostHTTPSPort)
			printf '%s' 'vhost_https_port'
			;;
		vhostHTTPTimeout)
			printf '%s' 'vhost_http_timeout'
			;;
		webServer.addr)
			printf '%s' 'dashboard_addr'
			;;
		webServer.port)
			printf '%s' 'dashboard_port'
			;;
		webServer.user)
			printf '%s' 'dashboard_user'
			;;
		webServer.password)
			printf '%s' 'dashboard_pwd'
			;;
		webServer.tls.enable)
			printf '%s' 'dashboard_tls_mode'
			;;
		webServer.tls.certFile)
			printf '%s' 'dashboard_tls_cert_file'
			;;
		webServer.tls.keyFile)
			printf '%s' 'dashboard_tls_key_file'
			;;
		webServer.assetsDir)
			printf '%s' 'assets_dir'
			;;
		log.to)
			printf '%s' 'log_file'
			;;
		log.level)
			printf '%s' 'log_level'
			;;
		log.maxDays)
			printf '%s' 'log_max_days'
			;;
		log.disablePrintColor)
			printf '%s' 'disable_log_color'
			;;
		auth.token)
			printf '%s' 'token'
			;;
		auth.oidc.issuer)
			printf '%s' 'oidc_issuer'
			;;
		auth.oidc.audience)
			printf '%s' 'oidc_audience'
			;;
		subdomainHost)
			printf '%s' 'subdomain_host'
			;;
		transport.tcpMux)
			printf '%s' 'tcp_mux'
			;;
		custom404Page)
			printf '%s' 'custom_404_page'
			;;
		allowPorts)
			printf '%s' 'allow_ports'
			;;
		maxPortsPerClient)
			printf '%s' 'max_ports_per_client'
			;;
		transport.heartbeatTimeout)
			printf '%s' 'heartbeat_timeout'
			;;
		*)
			return 1
			;;
	esac
}

_sync_main_includes_from_toml() {
	local value="$1"
	local item old_ifs

	[ -n "$value" ] || return 0

	old_ifs="$IFS"
	IFS=,
	for item in $value; do
		item="$(_trim_ws "$item")"
		item="${item#\"}"
		item="${item%\"}"
		[ -n "$item" ] || continue
		uci -q add_list "frps.main.conf_inc=$item"
	done
	IFS="$old_ifs"
}

_sync_allow_ports_from_toml() {
	local value="$1"
	local item single start end result sep old_ifs

	[ -n "$value" ] || return 0

	old_ifs="$IFS"
	IFS='}'
	for item in $value; do
		item="$(_trim_ws "${item#\{}")"
		item="${item#,}"
		item="$(_trim_ws "$item")"
		[ -n "$item" ] || continue

		single="$(printf '%s' "$item" | sed -n 's/.*single[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		if [ -n "$single" ]; then
			result="${result}${sep}${single}"
			sep=","
			continue
		fi

		start="$(printf '%s' "$item" | sed -n 's/.*start[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		end="$(printf '%s' "$item" | sed -n 's/.*end[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		if [ -n "$start" ] && [ -n "$end" ]; then
			result="${result}${sep}${start}-${end}"
			sep=","
		fi
	done
	IFS="$old_ifs"

	[ -n "$result" ] || return 0
	uci -q set "frps.common.allow_ports=$result"
}

_sync_common_from_toml() {
	local file="$1"
	local section=""
	local current_proxy=""
	local line key value opt
	local proxy_name

	[ -f "$file" ] || return 0
	config_load frps

	while IFS= read -r line || [ -n "$line" ]; do
		line="${line%$'\r'}"

		case "$line" in
			''|\#*|';'*)
				continue
				;;
			'[[proxies]]')
				section="proxy"
				current_proxy=""
				continue
				;;
			\[*\])
				section=""
				continue
				;;
		esac

		case "$line" in
			*=*)
				key="${line%%=*}"
				value="${line#*=}"
				;;
			*)
				continue
				;;
		esac

		key="${key%"${key##*[![:space:]]}"}"
		key="${key#"${key%%[![:space:]]*}"}"
		value="${value%"${value##*[![:space:]]}"}"
		value="${value#"${value%%[![:space:]]*}"}"

		if [ "$section" = "proxy" ]; then
			case "$key" in
				name)
					proxy_name="${value#\"}"
					proxy_name="${proxy_name%\"}"
					current_proxy="$(uci -q add frps conf)" || continue
					uci -q set "frps.$current_proxy.name=$proxy_name"
					continue
					;;
			esac
			[ -n "$current_proxy" ] || continue
			continue
		fi

		case "$key" in
			includes)
				value="${value#[}"
				value="${value%]}"
				value="$(printf '%s' "$value" | sed 's/"//g; s/[[:space:]]//g')"
				_sync_main_includes_from_toml "$value"
				continue
				;;
			allowPorts)
				value="${value#[}"
				value="${value%]}"
				_sync_allow_ports_from_toml "$value"
				continue
				;;
		esac

		opt="$(_sync_common_option "$key")" || continue
		case "$value" in
			true|false)
				[ -n "$value" ] && uci -q set "frps.common.$opt=$value"
				;;
			\"*\")
				value="${value#\"}"
				value="${value%\"}"
				uci -q set "frps.common.$opt=$value"
				;;
			*)
				[ -n "$value" ] && uci -q set "frps.common.$opt=$value"
				;;
		esac
	done < "$file"

	uci -q commit frps
}

_create_config() {
	local out="$1"
	local tmp
	tmp="$(mktemp /tmp/frps-XXXXXX)"

	_append_common "common" "$tmp"
	TOML_LIST=
	config_list_foreach main conf_inc _toml_collect_item
	[ -n "$TOML_LIST" ] && printf 'includes = [%s]\n' "$TOML_LIST" >> "$tmp"

	sed '/^$/d' "$tmp" > "$out"
	rm -f "$tmp"
}

start_service() {
	local sync_status
	local config_file
	sync_status="$(_read_sync_status)"

	if [ "$sync_status" = "uci" ]; then
		config_load frps
	else
		[ -f "$CONFIG_FOLDER/frps.toml" ] && _sync_common_from_toml "$CONFIG_FOLDER/frps.toml"
		config_load frps
	fi
	config_get_bool enabled common enabled 0
	[ "$enabled" = "1" ] || return 0
	test -d "$CONFIG_FOLDER" || mkdir -p "$CONFIG_FOLDER"
	config_file="$CONFIG_FOLDER/frps.toml"
	_create_config "$config_file"

	procd_open_instance "$NAME"
	procd_set_param command "$BIN" -c "$config_file"
	procd_set_param file "$config_file"

	config_get_bool stdout main stdout 0
	config_get_bool stderr main stderr 0
	config_get user main user
	config_get group main group
	config_get_bool respawn main respawn 1

	[ "$stdout" = "1" ] && procd_set_param stdout 1
	[ "$stderr" = "1" ] && procd_set_param stderr 1
	[ -n "$user" ] && procd_set_param user "$user"
	[ -n "$group" ] && procd_set_param group "$group"
	[ "$respawn" = "1" ] && procd_set_param respawn

	config_list_foreach main env _load_env
	procd_close_instance
}

reload_service() {
	_write_sync_status uci
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger frps
}
