#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

NAME="frpc"
BIN="/usr/bin/frpc"
CONFIG_FOLDER="/var/etc/$NAME"

_append_opt() {
	local file="$1"
	shift

	local key value
	for key in "$@"; do
		if printf '%s' "$key" | grep -q '='; then
			value="${key#*=}"
			key="${key%%=*}"
		else
			eval "value=\${$key}"
		fi
		[ -n "$value" ] || continue

		if printf '%s' "$key" | grep -qE 'addr|ip' && printf '%s' "$value" | grep -q ':'; then
			value="[$value]"
		fi

		printf '%s = %s\n' "$key" "$value" >> "$file"
	done
}

_append_list() {
	local file="$1"
	local key="$2"
	shift 2

	local item
	for item in "$@"; do
		[ -n "$item" ] || continue
		printf '%s\n' "$item" >> "$file"
	done
}

_append_common() {
	local section="$1"
	local file="$2"

	config_get server_addr "$section" server_addr
	config_get server_port "$section" server_port
	config_get http_proxy "$section" http_proxy
	config_get log_file "$section" log_file
	config_get log_level "$section" log_level
	config_get log_max_days "$section" log_max_days
	config_get disable_log_color "$section" disable_log_color
	config_get auth_method "$section" auth_method token
	config_get token "$section" token
	config_get oidc_client_id "$section" oidc_client_id
	config_get oidc_client_secret "$section" oidc_client_secret
	config_get oidc_audience "$section" oidc_audience
	config_get oidc_token_endpoint_url "$section" oidc_token_endpoint_url
	config_get admin_addr "$section" admin_addr
	config_get admin_port "$section" admin_port
	config_get admin_user "$section" admin_user
	config_get admin_pwd "$section" admin_pwd
	config_get assets_dir "$section" assets_dir
	config_get tcp_mux "$section" tcp_mux
	config_get user "$section" user
	config_get login_fail_exit "$section" login_fail_exit
	config_get protocol "$section" protocol
	config_get tls_enable "$section" tls_enable
	config_get heartbeat_interval "$section" heartbeat_interval
	config_get heartbeat_timeout "$section" heartbeat_timeout

	_append_opt "$file" \
		server_addr server_port http_proxy log_file log_level log_max_days \
		disable_log_color auth.method=auth_method admin_addr admin_port \
		admin_user admin_pwd assets_dir tcp_mux user login_fail_exit \
		protocol tls_enable heartbeat_interval heartbeat_timeout

	case "$auth_method" in
		oidc)
			_append_opt "$file" \
				auth.oidc.clientID=oidc_client_id \
				auth.oidc.clientSecret=oidc_client_secret \
				auth.oidc.audience=oidc_audience \
				auth.oidc.tokenEndpointURL=oidc_token_endpoint_url
			;;
		*)
			_append_opt "$file" token
			;;
	esac
}

_append_proxy() {
	local section="$1"
	local file="$2"

	[ "$section" = "common" ] && return 0

	config_get name "$section" name
	[ -n "$name" ] || return 0

	config_get type "$section" type
	config_get use_encryption "$section" use_encryption
	config_get use_compression "$section" use_compression
	config_get local_ip "$section" local_ip
	config_get local_port "$section" local_port
	config_get remote_port "$section" remote_port
	config_get role "$section" role
	config_get server_name "$section" server_name
	config_get bind_addr "$section" bind_addr
	config_get bind_port "$section" bind_port
	config_get sk "$section" sk
	config_get http_user "$section" http_user
	config_get http_pwd "$section" http_pwd
	config_get subdomain "$section" subdomain
	config_get custom_domains "$section" custom_domains
	config_get locations "$section" locations
	config_get host_header_rewrite "$section" host_header_rewrite
	config_get proxy_protocol_version "$section" proxy_protocol_version
	config_get group "$section" group
	config_get group_key "$section" group_key
	config_get health_check_type "$section" health_check_type
	config_get health_check_url "$section" health_check_url
	config_get health_check_timeout_s "$section" health_check_timeout_s
	config_get health_check_max_failed "$section" health_check_max_failed
	config_get health_check_interval_s "$section" health_check_interval_s
	config_get plugin "$section" plugin
	config_get plugin_http_user "$section" plugin_http_user
	config_get plugin_http_passwd "$section" plugin_http_passwd
	config_get plugin_user "$section" plugin_user
	config_get plugin_passwd "$section" plugin_passwd
	config_get plugin_unix_path "$section" plugin_unix_path
	config_get plugin_local_addr "$section" plugin_local_addr
	config_get plugin_local_path "$section" plugin_local_path
	config_get plugin_strip_prefix "$section" plugin_strip_prefix
	config_get plugin_crt_path "$section" plugin_crt_path
	config_get plugin_key_path "$section" plugin_key_path
	config_get plugin_host_header_rewrite "$section" plugin_host_header_rewrite
	config_get plugin_output_buffer_size "$section" plugin_output_buffer_size

	printf '\n[%s]\n' "$name" >> "$file"
	_append_opt "$file" \
		type use_encryption use_compression local_ip local_port remote_port role \
		server_name bind_addr bind_port sk http_user http_pwd subdomain \
		custom_domains locations host_header_rewrite proxy_protocol_version \
		group group_key health_check_type health_check_url health_check_timeout_s \
		health_check_max_failed health_check_interval_s plugin plugin_http_user \
		plugin_http_passwd plugin_user plugin_passwd plugin_unix_path \
		plugin_local_addr plugin_local_path plugin_strip_prefix plugin_crt_path \
		plugin_key_path plugin_host_header_rewrite plugin_output_buffer_size
}

_load_env() {
	local env="$1"
	[ -n "$env" ] || return 0
	procd_append_param env "$env"
}

_load_include() {
	local file="$1"
	[ -f "$file" ] || return 0
	cat "$file" >> "$2"
}

_trim_ws() {
	local value="$1"

	value="${value%"${value##*[![:space:]]}"}"
	value="${value#"${value%%[![:space:]]*}"}"
	printf '%s' "$value"
}

_toml_escape() {
	printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

_toml_quote() {
	printf '"%s"' "$(_toml_escape "$1")"
}

_toml_write_string() {
	local file="$1"
	local key="$2"
	local value="$3"

	[ -n "$value" ] || return 0
	printf '%s = %s\n' "$key" "$(_toml_quote "$value")" >> "$file"
}

_toml_write_bool() {
	local file="$1"
	local key="$2"
	local value="$3"

	case "$value" in
		1|true|TRUE|yes|on)
			printf '%s = true\n' "$key" >> "$file"
			;;
		0|false|FALSE|no|off)
			printf '%s = false\n' "$key" >> "$file"
			;;
	esac
}

_toml_write_int() {
	local file="$1"
	local key="$2"
	local value="$3"

	[ -n "$value" ] || return 0
	printf '%s = %s\n' "$key" "$value" >> "$file"
}

_toml_write_csv_array() {
	local file="$1"
	local key="$2"
	local value="$3"
	local item arr sep old_ifs

	[ -n "$value" ] || return 0

	old_ifs="$IFS"
	IFS=,
	for item in $value; do
		item="$(_trim_ws "$item")"
		[ -n "$item" ] || continue
		arr="${arr}${sep}$(_toml_quote "$item")"
		sep=", "
	done
	IFS="$old_ifs"

	[ -n "$arr" ] || return 0
	printf '%s = [%s]\n' "$key" "$arr" >> "$file"
}

_toml_write_allow_ports() {
	local file="$1"
	local value="$2"
	local old_ifs item part result sep single start end

	[ -n "$value" ] || return 0

	old_ifs="$IFS"
	IFS='}'
	for part in $value; do
		part="$(_trim_ws "${part#\{}")"
		part="${part#,}"
		part="$(_trim_ws "$part")"
		[ -n "$part" ] || continue

		single="$(printf '%s' "$part" | sed -n 's/.*single[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		if [ -n "$single" ]; then
			result="${result}${sep}{ single = $single }"
			sep=", "
			continue
		fi

		start="$(printf '%s' "$part" | sed -n 's/.*start[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		end="$(printf '%s' "$part" | sed -n 's/.*end[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		if [ -n "$start" ] && [ -n "$end" ]; then
			result="${result}${sep}{ start = $start, end = $end }"
			sep=", "
		fi
	done
	IFS="$old_ifs"

	[ -n "$result" ] || return 0
	printf 'allowPorts = [%s]\n' "$result" >> "$file"
}

_toml_collect_list_item() {
	local item="$1"

	[ -n "$item" ] || return 0

	if [ -n "$TOML_LIST" ]; then
		TOML_LIST="$TOML_LIST, $(_toml_quote "$item")"
	else
		TOML_LIST="$(_toml_quote "$item")"
	fi
}

_toml_collect_include_item() {
	_toml_collect_list_item "$1"
}

_find_proxy_section_by_name() {
	local section="$1"
	local target="$2"
	local name

	[ -n "$SYNC_PROXY_SECTION" ] && return 0

	config_get name "$section" name
	[ "$name" = "$target" ] && SYNC_PROXY_SECTION="$section"
}

_sync_proxy_section() {
	local name="$1"

	SYNC_PROXY_SECTION=""
	config_foreach _find_proxy_section_by_name conf "$name"
	if [ -n "$SYNC_PROXY_SECTION" ]; then
		printf '%s' "$SYNC_PROXY_SECTION"
		return 0
	fi

	SYNC_PROXY_SECTION="$(uci -q add frpc conf)" || return 1
	uci -q set "frpc.$SYNC_PROXY_SECTION.name=$name"
	printf '%s' "$SYNC_PROXY_SECTION"
}

_sync_proxy_delete_missing() {
	return 0
}

_sync_common_option() {
	case "$1" in
		server_addr|server_port|http_proxy|log_file|log_level|log_max_days|disable_log_color|auth_method|token|oidc_client_id|oidc_client_secret|oidc_audience|oidc_token_endpoint_url|admin_addr|admin_port|admin_user|admin_pwd|assets_dir|tcp_mux|user|login_fail_exit|protocol|tls_enable|heartbeat_interval|heartbeat_timeout|allow_ports|conf_inc)
			printf '%s' "$1"
			;;
		auth.method)
			printf '%s' 'auth_method'
			;;
		serverAddr)
			printf '%s' 'server_addr'
			;;
		serverPort)
			printf '%s' 'server_port'
			;;
		transport.proxyURL)
			printf '%s' 'http_proxy'
			;;
		log.to)
			printf '%s' 'log_file'
			;;
		log.level)
			printf '%s' 'log_level'
			;;
		log.maxDays)
			printf '%s' 'log_max_days'
			;;
		log.disablePrintColor)
			printf '%s' 'disable_log_color'
			;;
		auth.token)
			printf '%s' 'token'
			;;
		auth.oidc.clientID)
			printf '%s' 'oidc_client_id'
			;;
		auth.oidc.clientSecret)
			printf '%s' 'oidc_client_secret'
			;;
		auth.oidc.audience)
			printf '%s' 'oidc_audience'
			;;
		auth.oidc.tokenEndpointURL)
			printf '%s' 'oidc_token_endpoint_url'
			;;
		webServer.addr)
			printf '%s' 'admin_addr'
			;;
		webServer.port)
			printf '%s' 'admin_port'
			;;
		webServer.user)
			printf '%s' 'admin_user'
			;;
		webServer.password)
			printf '%s' 'admin_pwd'
			;;
		webServer.assetsDir)
			printf '%s' 'assets_dir'
			;;
		transport.tcpMux)
			printf '%s' 'tcp_mux'
			;;
		loginFailExit)
			printf '%s' 'login_fail_exit'
			;;
		transport.protocol)
			printf '%s' 'protocol'
			;;
		transport.tls.enable)
			printf '%s' 'tls_enable'
			;;
		transport.heartbeatInterval)
			printf '%s' 'heartbeat_interval'
			;;
		transport.heartbeatTimeout)
			printf '%s' 'heartbeat_timeout'
			;;
		*)
			return 1
			;;
	esac
}

_runtime_config_is_newer_than_uci() {
	local file="$1"
	local uci_file="/etc/config/$NAME"
	local file_mtime uci_mtime

	[ -f "$file" ] || return 1
	[ -f "$uci_file" ] || return 0

	file_mtime="$(stat -c '%Y' "$file" 2>/dev/null)" || return 0
	uci_mtime="$(stat -c '%Y' "$uci_file" 2>/dev/null)" || return 0

	[ "$file_mtime" -gt "$uci_mtime" ]
}

_align_runtime_config_mtime() {
	local file="$1"
	local uci_file="/etc/config/$NAME"

	[ -f "$file" ] || return 0
	[ -f "$uci_file" ] || return 0
	touch -r "$uci_file" "$file"
}

_append_common() {
	local section="$1"
	local file="$2"
	local auth_method token oidc_client_id oidc_client_secret oidc_audience oidc_token_endpoint_url
	local includes

	config_get server_addr "$section" server_addr
	config_get server_port "$section" server_port
	config_get http_proxy "$section" http_proxy
	config_get log_file "$section" log_file
	config_get log_level "$section" log_level
	config_get log_max_days "$section" log_max_days
	config_get_bool disable_log_color "$section" disable_log_color 0
	config_get auth_method "$section" auth_method token
	config_get token "$section" token
	config_get oidc_client_id "$section" oidc_client_id
	config_get oidc_client_secret "$section" oidc_client_secret
	config_get oidc_audience "$section" oidc_audience
	config_get oidc_token_endpoint_url "$section" oidc_token_endpoint_url
	config_get admin_addr "$section" admin_addr
	config_get admin_port "$section" admin_port
	config_get admin_user "$section" admin_user
	config_get admin_pwd "$section" admin_pwd
	config_get assets_dir "$section" assets_dir
	config_get_bool tcp_mux "$section" tcp_mux 1
	config_get user "$section" user
	config_get_bool login_fail_exit "$section" login_fail_exit 1
	config_get protocol "$section" protocol
	config_get_bool tls_enable "$section" tls_enable 0
	config_get heartbeat_interval "$section" heartbeat_interval
	config_get heartbeat_timeout "$section" heartbeat_timeout

	_toml_write_string "$file" serverAddr "$server_addr"
	_toml_write_int "$file" serverPort "$server_port"
	_toml_write_string "$file" transport.proxyURL "$http_proxy"
	_toml_write_string "$file" log.to "$log_file"
	_toml_write_string "$file" log.level "$log_level"
	_toml_write_int "$file" log.maxDays "$log_max_days"
	_toml_write_bool "$file" log.disablePrintColor "$disable_log_color"
	_toml_write_string "$file" auth.method "$auth_method"

	case "$auth_method" in
		oidc)
			_toml_write_string "$file" auth.oidc.clientID "$oidc_client_id"
			_toml_write_string "$file" auth.oidc.clientSecret "$oidc_client_secret"
			_toml_write_string "$file" auth.oidc.audience "$oidc_audience"
			_toml_write_string "$file" auth.oidc.tokenEndpointURL "$oidc_token_endpoint_url"
			;;
		*)
			_toml_write_string "$file" auth.token "$token"
			;;
	esac

	_toml_write_string "$file" webServer.addr "$admin_addr"
	_toml_write_int "$file" webServer.port "$admin_port"
	_toml_write_string "$file" webServer.user "$admin_user"
	_toml_write_string "$file" webServer.password "$admin_pwd"
	_toml_write_string "$file" webServer.assetsDir "$assets_dir"
	_toml_write_bool "$file" transport.tcpMux "$tcp_mux"
	_toml_write_string "$file" user "$user"
	_toml_write_bool "$file" loginFailExit "$login_fail_exit"
	_toml_write_string "$file" transport.protocol "$protocol"
	_toml_write_bool "$file" transport.tls.enable "$tls_enable"
	_toml_write_int "$file" transport.heartbeatInterval "$heartbeat_interval"
	_toml_write_int "$file" transport.heartbeatTimeout "$heartbeat_timeout"

	TOML_LIST=
	config_list_foreach main conf_inc _toml_collect_include_item
	[ -n "$TOML_LIST" ] && printf 'includes = [%s]\n' "$TOML_LIST" >> "$file"
}

_append_proxy() {
	local section="$1"
	local file="$2"
	local name

	[ "$section" = "common" ] && return 0

	config_get name "$section" name
	[ -n "$name" ] || return 0

	local type use_encryption use_compression local_ip local_port remote_port role server_name bind_addr bind_port sk
	local http_user http_pwd subdomain custom_domains locations proxy_protocol_version group group_key
	local health_check_type health_check_url health_check_timeout_s health_check_max_failed health_check_interval_s
	local plugin plugin_http_user plugin_http_passwd plugin_user plugin_passwd plugin_unix_path plugin_local_addr
	local plugin_local_path plugin_strip_prefix plugin_crt_path plugin_key_path plugin_host_header_rewrite
	local plugin_output_buffer_size

	config_get type "$section" type
	config_get_bool use_encryption "$section" use_encryption 0
	config_get_bool use_compression "$section" use_compression 0
	config_get local_ip "$section" local_ip
	config_get local_port "$section" local_port
	config_get remote_port "$section" remote_port
	config_get role "$section" role
	config_get server_name "$section" server_name
	config_get bind_addr "$section" bind_addr
	config_get bind_port "$section" bind_port
	config_get sk "$section" sk
	config_get http_user "$section" http_user
	config_get http_pwd "$section" http_pwd
	config_get subdomain "$section" subdomain
	config_get custom_domains "$section" custom_domains
	config_get locations "$section" locations
	config_get proxy_protocol_version "$section" proxy_protocol_version
	config_get group "$section" group
	config_get group_key "$section" group_key
	config_get health_check_type "$section" health_check_type
	config_get health_check_url "$section" health_check_url
	config_get health_check_timeout_s "$section" health_check_timeout_s
	config_get health_check_max_failed "$section" health_check_max_failed
	config_get health_check_interval_s "$section" health_check_interval_s
	config_get plugin "$section" plugin
	config_get plugin_http_user "$section" plugin_http_user
	config_get plugin_http_passwd "$section" plugin_http_passwd
	config_get plugin_user "$section" plugin_user
	config_get plugin_passwd "$section" plugin_passwd
	config_get plugin_unix_path "$section" plugin_unix_path
	config_get plugin_local_addr "$section" plugin_local_addr
	config_get plugin_local_path "$section" plugin_local_path
	config_get plugin_strip_prefix "$section" plugin_strip_prefix
	config_get plugin_crt_path "$section" plugin_crt_path
	config_get plugin_key_path "$section" plugin_key_path
	config_get plugin_host_header_rewrite "$section" plugin_host_header_rewrite
	config_get plugin_output_buffer_size "$section" plugin_output_buffer_size

	printf '\n[[proxies]]\n' >> "$file"
	_toml_write_string "$file" name "$name"
	_toml_write_string "$file" type "$type"
	_toml_write_bool "$file" transport.useEncryption "$use_encryption"
	_toml_write_bool "$file" transport.useCompression "$use_compression"
	_toml_write_string "$file" localIP "$local_ip"
	_toml_write_int "$file" localPort "$local_port"
	_toml_write_int "$file" remotePort "$remote_port"
	_toml_write_string "$file" role "$role"
	_toml_write_string "$file" serverName "$server_name"
	_toml_write_string "$file" bindAddr "$bind_addr"
	_toml_write_int "$file" bindPort "$bind_port"
	_toml_write_string "$file" secretKey "$sk"
	_toml_write_string "$file" httpUser "$http_user"
	_toml_write_string "$file" httpPassword "$http_pwd"
	_toml_write_string "$file" subdomain "$subdomain"
	_toml_write_csv_array "$file" customDomains "$custom_domains"
	_toml_write_csv_array "$file" locations "$locations"
	_toml_write_string "$file" transport.proxyProtocolVersion "$proxy_protocol_version"
	_toml_write_string "$file" loadBalancer.group "$group"
	_toml_write_string "$file" loadBalancer.groupKey "$group_key"
	_toml_write_string "$file" healthCheck.type "$health_check_type"
	_toml_write_string "$file" healthCheck.url "$health_check_url"
	_toml_write_int "$file" healthCheck.timeoutSeconds "$health_check_timeout_s"
	_toml_write_int "$file" healthCheck.maxFailed "$health_check_max_failed"
	_toml_write_int "$file" healthCheck.intervalSeconds "$health_check_interval_s"
	_toml_write_string "$file" plugin.type "$plugin"
	_toml_write_string "$file" plugin.httpUser "$plugin_http_user"
	_toml_write_string "$file" plugin.httpPassword "$plugin_http_passwd"
	_toml_write_string "$file" plugin.user "$plugin_user"
	_toml_write_string "$file" plugin.password "$plugin_passwd"
	_toml_write_string "$file" plugin.unixPath "$plugin_unix_path"
	_toml_write_string "$file" plugin.localAddr "$plugin_local_addr"
	_toml_write_string "$file" plugin.localPath "$plugin_local_path"
	_toml_write_string "$file" plugin.stripPrefix "$plugin_strip_prefix"
	_toml_write_string "$file" plugin.crtPath "$plugin_crt_path"
	_toml_write_string "$file" plugin.keyPath "$plugin_key_path"
	_toml_write_string "$file" plugin.hostHeaderRewrite "$plugin_host_header_rewrite"
	_toml_write_int "$file" plugin.outputBufferSize "$plugin_output_buffer_size"
}

_sync_proxy_option() {
	case "$1" in
		name|type|use_encryption|use_compression|local_ip|local_port|remote_port|role|server_name|bind_addr|bind_port|sk|http_user|http_pwd|subdomain|custom_domains|locations|proxy_protocol_version|group|group_key|health_check_type|health_check_url|health_check_timeout_s|health_check_max_failed|health_check_interval_s|plugin|plugin_http_user|plugin_http_passwd|plugin_user|plugin_passwd|plugin_unix_path|plugin_local_addr|plugin_local_path|plugin_strip_prefix|plugin_crt_path|plugin_key_path|plugin_host_header_rewrite|plugin_output_buffer_size)
			printf '%s' "$1"
			;;
		transport.useEncryption)
			printf '%s' 'use_encryption'
			;;
		transport.useCompression)
			printf '%s' 'use_compression'
			;;
		localIP)
			printf '%s' 'local_ip'
			;;
		localPort)
			printf '%s' 'local_port'
			;;
		remotePort)
			printf '%s' 'remote_port'
			;;
		serverName)
			printf '%s' 'server_name'
			;;
		bindAddr)
			printf '%s' 'bind_addr'
			;;
		bindPort)
			printf '%s' 'bind_port'
			;;
		secretKey)
			printf '%s' 'sk'
			;;
		httpUser)
			printf '%s' 'http_user'
			;;
		httpPassword)
			printf '%s' 'http_pwd'
			;;
		customDomains)
			printf '%s' 'custom_domains'
			;;
		loadBalancer.group)
			printf '%s' 'group'
			;;
		loadBalancer.groupKey)
			printf '%s' 'group_key'
			;;
		healthCheck.type)
			printf '%s' 'health_check_type'
			;;
		healthCheck.url)
			printf '%s' 'health_check_url'
			;;
		healthCheck.timeoutSeconds)
			printf '%s' 'health_check_timeout_s'
			;;
		healthCheck.maxFailed)
			printf '%s' 'health_check_max_failed'
			;;
		healthCheck.intervalSeconds)
			printf '%s' 'health_check_interval_s'
			;;
		plugin.type)
			printf '%s' 'plugin'
			;;
		plugin.httpUser)
			printf '%s' 'plugin_http_user'
			;;
		plugin.httpPassword)
			printf '%s' 'plugin_http_passwd'
			;;
		plugin.user)
			printf '%s' 'plugin_user'
			;;
		plugin.password)
			printf '%s' 'plugin_passwd'
			;;
		plugin.unixPath)
			printf '%s' 'plugin_unix_path'
			;;
		plugin.localAddr)
			printf '%s' 'plugin_local_addr'
			;;
		plugin.localPath)
			printf '%s' 'plugin_local_path'
			;;
		plugin.stripPrefix)
			printf '%s' 'plugin_strip_prefix'
			;;
		plugin.crtPath)
			printf '%s' 'plugin_crt_path'
			;;
		plugin.keyPath)
			printf '%s' 'plugin_key_path'
			;;
		plugin.hostHeaderRewrite)
			printf '%s' 'plugin_host_header_rewrite'
			;;
		plugin.outputBufferSize)
			printf '%s' 'plugin_output_buffer_size'
			;;
		transport.proxyProtocolVersion)
			printf '%s' 'proxy_protocol_version'
			;;
		*)
			return 1
			;;
	esac
}

_sync_main_includes_from_toml() {
	local value="$1"
	local item old_ifs

	[ -n "$value" ] || return 0

	old_ifs="$IFS"
	IFS=,
	for item in $value; do
		item="$(_trim_ws "$item")"
		item="${item#\"}"
		item="${item%\"}"
		[ -n "$item" ] || continue
		uci -q add_list "frpc.main.conf_inc=$item"
	done
	IFS="$old_ifs"
}

_sync_allow_ports_from_toml() {
	local value="$1"
	local item single start end result sep
	local old_ifs

	[ -n "$value" ] || return 0

	old_ifs="$IFS"
	IFS='}'
	for item in $value; do
		item="$(_trim_ws "${item#\{}")"
		item="${item#,}"
		item="$(_trim_ws "$item")"
		[ -n "$item" ] || continue

		single="$(printf '%s' "$item" | sed -n 's/.*single[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		if [ -n "$single" ]; then
			result="${result}${sep}${single}"
			sep=","
			continue
		fi

		start="$(printf '%s' "$item" | sed -n 's/.*start[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		end="$(printf '%s' "$item" | sed -n 's/.*end[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p')"
		if [ -n "$start" ] && [ -n "$end" ]; then
			result="${result}${sep}${start}-${end}"
			sep=","
		fi
	done
	IFS="$old_ifs"

	[ -n "$result" ] || return 0
	uci -q set "frpc.common.allow_ports=$result"
}

_sync_common_from_toml() {
	local file="$1"
	local section=""
	local current_proxy=""
	local line key value opt
	local proxy_name
	local seen

	[ -f "$file" ] || return 0
	config_load frpc
	seen="$(mktemp /tmp/frpc-proxy-seen-XXXXXX)" || return 1

	while IFS= read -r line || [ -n "$line" ]; do
		line="${line%$'\r'}"

		case "$line" in
			''|\#*|';'*)
				continue
				;;
			'[[proxies]]')
				section="proxy"
				current_proxy=""
				continue
				;;
			\[*\])
				section=""
				continue
				;;
		esac

		case "$line" in
			*=*)
				key="${line%%=*}"
				value="${line#*=}"
				;;
			*)
				continue
				;;
		esac

		key="$(_trim_ws "$key")"
		value="$(_trim_ws "$value")"

		if [ "$section" = "proxy" ]; then
			opt="$(_sync_proxy_option "$key")" || continue
			case "$key" in
				name)
					proxy_name="${value#\"}"
					proxy_name="${proxy_name%\"}"
					current_proxy="$(_sync_proxy_section "$proxy_name")" || continue
					printf '%s\n' "$proxy_name" >> "$seen"
					continue
					;;
				customDomains|locations)
					value="${value#[}"
					value="${value%]}"
					value="$(printf '%s' "$value" | sed 's/"//g; s/[[:space:]]//g')"
					;;
			esac

			[ -n "$current_proxy" ] || continue

			case "$value" in
				true|false)
					uci -q set "frpc.$current_proxy.$opt=$value"
					;;
				\"*\")
					value="${value#\"}"
					value="${value%\"}"
					uci -q set "frpc.$current_proxy.$opt=$value"
					;;
				\[*\])
					value="${value#[}"
					value="${value%]}"
					value="$(printf '%s' "$value" | sed 's/"//g; s/[[:space:]]//g')"
					uci -q set "frpc.$current_proxy.$opt=$value"
					;;
				*)
					[ -n "$value" ] && uci -q set "frpc.$current_proxy.$opt=$value"
					;;
			esac
			continue
		fi

		case "$key" in
			includes)
				value="${value#[}"
				value="${value%]}"
				value="$(printf '%s' "$value" | sed 's/"//g; s/[[:space:]]//g')"
				_sync_main_includes_from_toml "$value"
				continue
				;;
		esac

		opt="$(_sync_common_option "$key")" || continue
		case "$key" in
			custom_404_page|serverAddr|serverPort|transport.proxyURL|log.to|log.level|webServer.addr|webServer.user|webServer.password|webServer.assetsDir|user|transport.protocol|transport.heartbeatInterval|transport.heartbeatTimeout|auth.method|auth.token|auth.oidc.clientID|auth.oidc.clientSecret|auth.oidc.audience|auth.oidc.tokenEndpointURL)
				;;
		esac

		case "$value" in
			true|false)
				uci -q set "frpc.common.$opt=$value"
				;;
			\"*\")
				value="${value#\"}"
				value="${value%\"}"
				uci -q set "frpc.common.$opt=$value"
				;;
			\[*\])
				case "$key" in
					allowPorts)
						value="${value#[}"
						value="${value%]}"
						_sync_allow_ports_from_toml "$value"
						;;
				esac
				;;
			*)
				[ -n "$value" ] && uci -q set "frpc.common.$opt=$value"
				;;
		esac
	done < "$file"

	rm -f "$seen"

	uci -q commit frpc
}

_create_config() {
	local out="$1"
	local tmp
	tmp="$(mktemp /tmp/frpc-XXXXXX)"

	_append_common "common" "$tmp"

	config_foreach _append_proxy conf "$tmp"

	sed '/^$/d' "$tmp" > "$out"
	rm -f "$tmp"
}

start_service() {
	if _runtime_config_is_newer_than_uci "$CONFIG_FOLDER/frpc.toml"; then
		_sync_common_from_toml "$CONFIG_FOLDER/frpc.toml"
	fi

	config_load frpc
	config_get_bool enabled common enabled 0
	[ "$enabled" = "1" ] || return 0
	test -d "$CONFIG_FOLDER" || mkdir -p "$CONFIG_FOLDER"

	local config_file="$CONFIG_FOLDER/frpc.toml"
	_create_config "$config_file"
	_align_runtime_config_mtime "$config_file"

	procd_open_instance "$NAME"
	procd_set_param command "$BIN" -c "$config_file"
	procd_set_param file "$config_file"

	config_get_bool stdout main stdout 0
	config_get_bool stderr main stderr 0
	config_get user main user
	config_get group main group
	config_get_bool respawn main respawn 1

	[ "$stdout" = "1" ] && procd_set_param stdout 1
	[ "$stderr" = "1" ] && procd_set_param stderr 1
	[ -n "$user" ] && procd_set_param user "$user"
	[ -n "$group" ] && procd_set_param group "$group"
	[ "$respawn" = "1" ] && procd_set_param respawn

	config_list_foreach main env _load_env
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger frpc
}
